name: FriedAmida Release

on:
  push:
    branches:
      - master

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build_project:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectName:
          - FriedAmida
        unityVersion:
          - 2018.4.20f1
        targetPlatform:
          - Android
          - WebGL

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: webbertakken/unity-test-runner@v1.6
        id: testRunner
        with:
          unityVersion: ${{ matrix.unityVersion }}

      - uses: actions/upload-artifact@v1
        with:
          name: Test results (all modes)
          path: ${{ steps.testRunner.outputs.artifactsPath }}

      - uses: webbertakken/unity-builder@v0.12
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}

      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build

      - uses: peaceiris/actions-gh-pages@v3.5.7
        if: matrix.targetPlatform == 'WebGL'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/WebGL/WebGL

      - uses: 8398a7/action-slack@v3.0.0
        if: success() && matrix.targetPlatform == 'WebGL'
        with:
          status: success
          text: Upload to https://koob1999.github.io/FriedAmida
          author_name: Release success !!!
          username: GitHub Actions
          mention: here
          channel: '#team-sophomore-notification'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
